space = ' '
initial = 'A' | 'B' | 'C' | 'D' | 'E' | 'F' | 'G' | 'H' | 'I' | 'J' | 'K' | 'L' | 'M' | 'N' | 'O' | 'P' | 'Q' | 'R' | 'S' | 'T' | 'U' | 'V' | 'W' | 'X' | 'Y' | 'Z'
female-first-name = 'Emma' | 'Jane' | 'Liz' | 'Mary' | 'Jenny'
male-first-name = 'John' | 'Frank' | 'Sam' | 'Rob'
last-name = 'Smith' | 'Richards' | 'Harrison' | 'Murphy' | 'Turing' | 'Freeman'
female-personal-part = initial . '.' | female-first-name
male-personal-part = initial . '.' | male-first-name
female-name-part = female-personal-part . space . last-name | female-personal-part . space . female-name-part
male-name-part = male-personal-part . space . last-name . opt-suffix-part | male-personal-part . space . male-name-part
opt-suffix-part = ' Sr.' | ' Jr.' | ''
name = female-name-part | male-name-part
